---------------------------- MODULE MoqtVerCtl ----------------------------
(***************************************************************************)
(* Ledger 7-1 (a): version negotiation + the control-stream pair.          *)
(*                                                                         *)
(* One wired hub (server) and a set of independent client sessions.        *)
(* Version is chosen ONLY by the WebTransport subprotocol (WT-Available-   *)
(* Protocols / WT-Protocol), draft-18/19 3.1, draft-22 6.2; SETUP is       *)
(* byte-identical across 18/19/22 and carries no version.                  *)
(*                                                                         *)
(* Hub behaviour is transcribed from (main tree, 2026-10-05):              *)
(*   srvrun.c:6214  srvrun_wt_select   first client-offer member that the  *)
(*                                     server list contains                *)
(*   moqtrun.c:251  moqtrun_negotiated_ver  unknown/empty -> draft-19      *)
(*   moqtrun.c:259  moqtrun_legacy_token    empty/unlisted -> legacy bidi  *)
(*   moqtrun.c:184  moqtrun_ctl_open   uni (token) / bidi (legacy) + SETUP *)
(*   moqtrun.c:5935 moqtrun_fresh_uni_ctl   classify first varint 0x2F00   *)
(*   moqtrun.c:5951 moqtrun_hold_gate  legacy: !ctl_opened,                *)
(*                                     token : !moqsess_established        *)
(*   moqtrun.c:6060 moqtrun_dispatch_data_stream  a held stream stays held *)
(*   moqtrun.c:3851 moqtrun_setup_second  2nd SETUP -> PROTOCOL_VIOLATION   *)
(*                                                                         *)
(* A client's control-stream bytes are a script of chunks (one transport   *)
(* delivery each):                                                         *)
(*   "S" = a delivery that starts with SETUP's whole Type varint (0x2F00)  *)
(*   "H" = a delivery holding ONLY the first byte of that 2-byte varint    *)
(*   "R" = the rest of the SETUP after an "H"                              *)
(*   "M" = any other control message                                       *)
(* QUIC (RFC 9000 2.2) lets a peer split a stream at any byte, so "H","R"  *)
(* is a legal delivery pattern; srvrun delivers each contiguous delta      *)
(* (srvrun.c:2408 srvrun_deliver_wt_stream_delta).                         *)
(***************************************************************************)
EXTENDS Naturals, Sequences, FiniteSets, TLC

CONSTANTS
  Peers,       \* client sessions
  Offers,      \* set of WT-Available-Protocols offers (client preference order)
  ServerList,  \* srvrun wt_protocols (generated by wired_moqt_wt_protocols)
  Table,       \* tokens moqver_table knows
  CtlScripts,  \* client control-stream delivery scripts
  FixSplit     \* TRUE = proposed fix: an INSUFFICIENT first varint waits
               \* for more bytes instead of being classified (fix check)

Range(s) == {s[i] : i \in DOMAIN s}

\* srvrun_wt_select: client preference order, first member the server lists.
Select(o) ==
  LET idx == {i \in 1..Len(o) : o[i] \in Range(ServerList)}
  IN IF idx = {} THEN "none"
     ELSE o[CHOOSE i \in idx : \A j \in idx : i <= j]

VARIABLES
  phase,     \* "idle" | "up" | "aborted" | "closed"
  offer,     \* the client's offer
  token,     \* the subprotocol both sides learned ("none" = no WT-Protocol)
  hver,      \* hub's peer->ver ("none" before on_session)
  legacy,    \* hub's peer->legacy
  cver,      \* client's view of the version (= token it received)
  hubCtl,    \* "none" | "uni" | "bidi": hub's own control stream
  setupRecv, \* hub accepted the client's SETUP
  nSetup,    \* SETUPs the hub dispatched for this peer
  peerCtl,   \* hub adopted the client's control stream
  asm,       \* hub's reassembly of the adopted control stream
  held,      \* client streams in the hold log ("cu" ctl uni, "cq" request)
  ctlQ,      \* undelivered control-stream chunks
  reqQ,      \* undelivered request-stream chunks
  first,     \* first control message the hub processed: "none"|"S"|"M"
  reqDone,   \* the client's request was processed
  reqEarly,  \* a request was processed while the hold gate was closed
  sent       \* set of draft versions the hub encoded messages to p in

vars == <<phase, offer, token, hver, legacy, cver, hubCtl, setupRecv,
          nSetup, peerCtl, asm, held, ctlQ, reqQ, first, reqDone,
          reqEarly, sent>>

Browser(p) == offer[p] = <<>>          \* cannot negotiate a WT subprotocol
Est(p)     == hubCtl[p] # "none" /\ setupRecv[p]   \* moqsess_established
HoldGate(p) == IF legacy[p] THEN hubCtl[p] = "none" ELSE ~Est(p)

TypeOK ==
  /\ phase \in [Peers -> {"idle", "up", "aborted", "closed"}]
  /\ hubCtl \in [Peers -> {"none", "uni", "bidi"}]
  /\ first \in [Peers -> {"none", "S", "M"}]
  /\ held \in [Peers -> SUBSET {"cu", "cq"}]
  /\ nSetup \in [Peers -> 0..3]

Init ==
  /\ phase = [p \in Peers |-> "idle"]
  /\ offer = [p \in Peers |-> <<>>]
  /\ token = [p \in Peers |-> "none"]
  /\ hver = [p \in Peers |-> "none"]
  /\ legacy = [p \in Peers |-> FALSE]
  /\ cver = [p \in Peers |-> "none"]
  /\ hubCtl = [p \in Peers |-> "none"]
  /\ setupRecv = [p \in Peers |-> FALSE]
  /\ nSetup = [p \in Peers |-> 0]
  /\ peerCtl = [p \in Peers |-> FALSE]
  /\ asm = [p \in Peers |-> <<>>]
  /\ held = [p \in Peers |-> {}]
  /\ ctlQ = [p \in Peers |-> <<>>]
  /\ reqQ = [p \in Peers |-> <<>>]
  /\ first = [p \in Peers |-> "none"]
  /\ reqDone = [p \in Peers |-> FALSE]
  /\ reqEarly = [p \in Peers |-> FALSE]
  /\ sent = [p \in Peers |-> {}]

(* Extended CONNECT + 2xx: both ends learn the same token (WT-Protocol).
   A client that offered moqt-NN tokens but got none back cannot agree on
   a version and gives up (modelled as "aborted"); a browser offers none
   and speaks the legacy single-bidi binding without SETUP (ruling 9-3). *)
Connect(p) ==
  /\ phase[p] = "idle"
  /\ \E o \in Offers, s \in CtlScripts :
       LET tk == Select(o) IN
       /\ offer' = [offer EXCEPT ![p] = o]
       /\ token' = [token EXCEPT ![p] = tk]
       /\ hver' = [hver EXCEPT ![p] = IF tk \in Table THEN tk ELSE "19"]
       /\ legacy' = [legacy EXCEPT ![p] = (tk = "none" \/ tk \notin Table)]
       /\ cver' = [cver EXCEPT ![p] = tk]
       /\ phase' = [phase EXCEPT ![p] =
                      IF o # <<>> /\ tk = "none" THEN "aborted" ELSE "up"]
       /\ ctlQ' = [ctlQ EXCEPT ![p] = IF o = <<>> THEN <<"M">> ELSE s]
       /\ reqQ' = [reqQ EXCEPT ![p] = <<"Q">>]
  /\ UNCHANGED <<hubCtl, setupRecv, nSetup, peerCtl, asm, held, first,
                 reqDone, reqEarly, sent>>

(* moqtrun_ctl_open: the open may be refused and retried (ctl_retry); the
   SETUP is the stream's first bytes, so "opened" == "SETUP sent". *)
HubOpenCtl(p) ==
  /\ phase[p] = "up"
  /\ hubCtl[p] = "none"
  /\ hubCtl' = [hubCtl EXCEPT ![p] = IF legacy[p] THEN "bidi" ELSE "uni"]
  /\ sent' = [sent EXCEPT ![p] = @ \cup {hver[p]}]
  /\ UNCHANGED <<phase, offer, token, hver, legacy, cver, setupRecv, nSetup,
                 peerCtl, asm, held, ctlQ, reqQ, first, reqDone, reqEarly>>

(* Dispatch of one complete control message m from the client. *)
CtlMsg(p, m) ==
  /\ first' = [first EXCEPT ![p] = IF @ = "none" THEN m ELSE @]
  /\ IF m = "S"
       THEN /\ nSetup' = [nSetup EXCEPT ![p] = @ + 1]
            /\ IF setupRecv[p]
                 THEN /\ phase' = [phase EXCEPT ![p] = "closed"]
                      /\ UNCHANGED setupRecv
                 ELSE /\ setupRecv' = [setupRecv EXCEPT ![p] = TRUE]
                      /\ UNCHANGED phase
       ELSE UNCHANGED <<nSetup, setupRecv, phase>>

\* The fresh-stream path's chunk as the C code sees it.
FreshCtl(p, c) ==
  CASE c = "S" ->                           \* classify == CONTROL: adopt
         /\ peerCtl' = [peerCtl EXCEPT ![p] = TRUE]
         /\ CtlMsg(p, "S")
         /\ UNCHANGED <<held, asm>>
    [] c = "H" /\ FixSplit ->               \* fix: keep reading, then adopt
         /\ peerCtl' = [peerCtl EXCEPT ![p] = TRUE]
         /\ asm' = [asm EXCEPT ![p] = <<"H">>]
         /\ UNCHANGED <<held, first, nSetup, setupRecv, phase>>
    [] c = "H" /\ HoldGate(p) ->            \* INSUFFICIENT: not control
         /\ held' = [held EXCEPT ![p] = @ \cup {"cu"}]
         /\ UNCHANGED <<peerCtl, asm, first, nSetup, setupRecv, phase>>
    [] OTHER ->                             \* data path: bytes are lost
         UNCHANGED <<held, peerCtl, asm, first, nSetup, setupRecv, phase>>

DeliverCtl(p) ==
  /\ phase[p] = "up"
  /\ ctlQ[p] # <<>>
  /\ Browser(p) => hubCtl[p] = "bidi"       \* writes back on the hub's bidi
  /\ LET c == Head(ctlQ[p]) IN
       CASE Browser(p) ->                   \* moqtrun_rx_is_own_ctl
              /\ CtlMsg(p, c)
              /\ UNCHANGED <<held, peerCtl, asm>>
         [] "cu" \in held[p] ->             \* hold_has: stays held
              UNCHANGED <<held, peerCtl, asm, first, nSetup, setupRecv, phase>>
         [] peerCtl[p] ->                   \* moqtrun_ctl_rx reassembly
              /\ IF asm[p] = <<"H">> /\ c = "R"
                   THEN CtlMsg(p, "S") ELSE CtlMsg(p, c)
              /\ asm' = [asm EXCEPT ![p] = <<>>]
              /\ UNCHANGED <<held, peerCtl>>
         [] OTHER -> FreshCtl(p, c)
  /\ ctlQ' = [ctlQ EXCEPT ![p] = Tail(@)]
  /\ UNCHANGED <<offer, token, hver, legacy, cver, hubCtl, reqQ, reqDone,
                 reqEarly, sent>>

ProcessReq(p) ==
  /\ reqDone' = [reqDone EXCEPT ![p] = TRUE]
  \* judged from the spec's own condition, not from the C gate under test
  /\ reqEarly' = [reqEarly EXCEPT ![p] =
                    @ \/ hubCtl[p] = "none" \/ (~legacy[p] /\ ~Est(p))]
  /\ sent' = [sent EXCEPT ![p] = @ \cup {hver[p]}]   \* reply in p->ver

DeliverReq(p) ==
  /\ phase[p] = "up"
  /\ reqQ[p] # <<>>
  /\ IF HoldGate(p) \/ "cq" \in held[p]
       THEN /\ held' = [held EXCEPT ![p] = @ \cup {"cq"}]
            /\ UNCHANGED <<reqDone, reqEarly, sent>>
       ELSE /\ ProcessReq(p)
            /\ UNCHANGED held
  /\ reqQ' = [reqQ EXCEPT ![p] = Tail(@)]
  /\ UNCHANGED <<phase, offer, token, hver, legacy, cver, hubCtl, setupRecv,
                 nSetup, peerCtl, asm, ctlQ, first>>

(* moqtrun_hold_replay: once the gate lifts every held record replays.
   A held "cu" record re-enters the fresh-uni path record by record; the
   one-byte "H" record alone is still INSUFFICIENT, so it is lost. *)
Replay(p) ==
  /\ phase[p] = "up"
  /\ held[p] # {}
  /\ ~HoldGate(p)
  /\ held' = [held EXCEPT ![p] = {}]
  /\ IF "cq" \in held[p] THEN ProcessReq(p)
                         ELSE UNCHANGED <<reqDone, reqEarly, sent>>
  /\ UNCHANGED <<phase, offer, token, hver, legacy, cver, hubCtl, setupRecv,
                 nSetup, peerCtl, asm, ctlQ, reqQ, first>>

(* GOAWAY from the hub (moqtrun_goaway_target needs ctl_opened). *)
HubGoaway(p) ==
  /\ phase[p] = "up"
  /\ hubCtl[p] # "none"
  /\ sent' = [sent EXCEPT ![p] = @ \cup {hver[p]}]
  /\ UNCHANGED <<phase, offer, token, hver, legacy, cver, hubCtl, setupRecv,
                 nSetup, peerCtl, asm, held, ctlQ, reqQ, first, reqDone,
                 reqEarly>>

Next == \E p \in Peers :
          Connect(p) \/ HubOpenCtl(p) \/ DeliverCtl(p) \/ DeliverReq(p)
          \/ Replay(p) \/ HubGoaway(p)

Fair == \A p \in Peers :
          /\ WF_vars(Connect(p)) /\ WF_vars(HubOpenCtl(p))
          /\ WF_vars(DeliverCtl(p)) /\ WF_vars(DeliverReq(p))
          /\ WF_vars(Replay(p))

Spec == Init /\ [][Next]_vars /\ Fair

(***************************** safety ************************************)

\* Both ends hold the same version; the binding follows the token.
VersionAgree ==
  \A p \in Peers : phase[p] = "up" =>
     /\ (cver[p] = "none") = legacy[p]
     /\ cver[p] # "none" => hver[p] = cver[p]

\* uni pair iff a moqt-NN token was negotiated (draft-17+ 3.3 / 22 6.3).
BindingAgree ==
  \A p \in Peers : hubCtl[p] # "none" =>
     ((hubCtl[p] = "uni") <=> (token[p] \in Table))

\* Token session: the peer's SETUP is the first control message the hub
\* acts on (22 9.1 "SETUP is the first message each endpoint sends on its
\* control stream"). A legacy browser session is exempt by ruling 9-3.
SetupFirst ==
  \A p \in Peers : ~legacy[p] => first[p] \in {"none", "S"}

\* At most one SETUP is accepted; a second one closes the session.
OneSetup == \A p \in Peers : nSetup[p] > 1 => phase[p] = "closed"

\* No request is acted on before setup completes (22 6.3 buffering).
NoEarlyRequest == \A p \in Peers : ~reqEarly[p]

\* Every message the hub sent p was encoded in p's negotiated version,
\* and nothing at all went out before the hub's own SETUP.
SentInPeerVersion ==
  \A p \in Peers :
     /\ sent[p] \subseteq {hver[p]}
     /\ sent[p] # {} => hubCtl[p] # "none"

Safety == TypeOK /\ VersionAgree /\ BindingAgree /\ SetupFirst /\ OneSetup
          /\ NoEarlyRequest /\ SentInPeerVersion

\* The negotiated version never changes once chosen.
VersionFixed ==
  [][\A p \in Peers : hver[p] # "none" => hver'[p] = hver[p]]_vars

(***************************** liveness **********************************)

\* A token session whose client follows the spec gets established.
EventuallyEstablished ==
  \A p \in Peers :
     (phase[p] = "up" /\ ~legacy[p]) ~> (Est(p) \/ phase[p] = "closed")

\* The client's first request is eventually acted on.
RequestAnswered ==
  \A p \in Peers : (phase[p] = "up") ~> (reqDone[p] \/ phase[p] = "closed")
=============================================================================
