#!/usr/bin/env python3
"""Convert Wycheproof testvectors_v1 JSON files into C arrays for the tests.

Usage: scripts/gen_wycheproof_vectors.py tests/vectors/wycheproof/<f>.json [...]
Writes tests/vectors/wycheproof/<stem>.h. Each case keeps its tcId, result
(valid / invalid / acceptable), flags and the group + test fields as the
JSON's raw hex text; tests/vectors/wycheproof/wyc_vec.h reads them. Nothing
here computes an expected value: every expectation comes from the JSON.
Redundant key encodings (DER, PEM, JWK, ASN) are dropped; the raw key
fields (publicKey.*) are kept.
"""
import json
import os
import re
import sys

DROP = {'tests', 'source', 'type', 'publicKeyDer', 'publicKeyPem',
        'publicKeyJwk', 'publicKeyAsn', 'keyJwk', 'comment'}
RESULT = {'valid': 0, 'invalid': 1, 'acceptable': 2}


def c_str(s):
    return '"' + str(s).replace('\\', '\\\\').replace('"', '\\"') + '"'


def flatten(prefix, obj, out):
    for k, v in obj.items():
        if k in DROP:
            continue
        if isinstance(v, dict):
            flatten(prefix + k + '.', v, out)
        elif not isinstance(v, list):
            out.append((prefix + k, v))


def emit(path):
    stem = re.sub(r'\W', '_', os.path.splitext(os.path.basename(path))[0])
    data = json.load(open(path, encoding='utf-8'))
    attrs, rows = [], []
    for g in data['testGroups']:
        gattrs = []
        flatten('g.', g, gattrs)
        for t in g['tests']:
            kv = list(gattrs)
            flatten('', {k: v for k, v in t.items()
                         if k not in ('tcId', 'result', 'flags')}, kv)
            rows.append((t['tcId'], RESULT[t['result']],
                         ','.join(t.get('flags', [])), len(attrs), len(kv)))
            attrs.extend(kv)
    out = os.path.join(os.path.dirname(path), stem + '.h')
    with open(out, 'w', encoding='utf-8') as f:
        f.write('/* clang-format off */\n')
        f.write(f'/* Generated by scripts/gen_wycheproof_vectors.py from\n'
                f' * {os.path.basename(path)}. Do not edit. */\n')
        f.write(f'static const bssl_attr wyc_{stem}_attrs[] = {{\n')
        for k, v in attrs:
            f.write(f'  {{{c_str(k)}, {c_str(v)}}},\n')
        f.write('};\n')
        f.write(f'static const wyc_case wyc_{stem}_cases[] = {{\n')
        for tc, res, flags, off, n in rows:
            f.write(f'  {{{tc}, {res}, {c_str(flags)}, {off}, {n}}},\n')
        f.write('};\n/* clang-format on */\n')
    print(f'{out}: {len(rows)} cases')


for p in sys.argv[1:]:
    emit(p)
