#!/bin/sh
# Generate build.ninja covering every build variant this repo has: the
# freestanding per-object compile (proves libc independence), the hosted
# unity-build test binary, and the three libFuzzer harnesses. Each variant
# needs its own rule (different flags = different .o ABI, so they can't share
# object files), but all four live in one build.ninja so `ninja` alone builds
# everything and `ninja <target>` builds just one.
set -eu

cc="${CC:-clang}"
# Flag sets come from justfile (single source of truth), passed as env vars.
: "${CFLAGS:?CFLAGS not set -- run via 'just ninja'}"
: "${TESTFLAGS:?TESTFLAGS not set -- run via 'just ninja'}"
: "${FUZZFLAGS:?FUZZFLAGS not set -- run via 'just ninja'}"

{
    echo "# generated by scripts/gen_ninja.sh -- do not edit"
    echo "cc = $cc"
    echo "cflags = $CFLAGS"
    echo "testflags = $TESTFLAGS"
    echo "fuzzflags = $FUZZFLAGS"
    echo
    echo "rule cc_freestanding"
    echo "  command = \$cc \$cflags -MD -MF \$out.d -c \$in -o \$out"
    echo "  depfile = \$out.d"
    echo "  deps = gcc"
    echo "  description = CC \$out"
    echo
    echo "rule cc_hosted_bin"
    echo "  command = \$cc \$testflags \$in -o \$out"
    echo "  description = CC \$out"
    echo
    echo "rule cc_fuzz_bin"
    echo "  command = \$cc \$fuzzflags \$in -o \$out"
    echo "  description = CC \$out"
    echo
    echo "# freestanding: every src/**.c to build/<path>.o (path-qualified,"
    echo "# avoids basename collisions). Proves libc independence per file."
    objs=""
    find src -name '*.c' | sort | while read -r f; do
        echo "build build/${f%.c}.o: cc_freestanding $f"
    done
    objs=$(find src -name '*.c' | sort | sed 's|^|build/|; s|\.c$|.o|' | tr '\n' ' ')
    echo
    echo "# hosted: tests/run.c is a unity build (includes every src/**.c and"
    echo "# *_test.c once), so it compiles straight to a binary -- no per-file"
    echo "# objects to track here."
    echo "build build/quic_test: cc_hosted_bin tests/run.c"
    echo
    echo "# fuzz: each harness includes its target src/**.c directly (hosted,"
    echo "# ASan+libFuzzer instrumented), same reasoning as the unity build."
    for name in header qpack x509; do
        echo "build fuzz/fuzz_$name: cc_fuzz_bin fuzz/fuzz_$name.c"
    done
    echo
    echo "# 'ninja' with no args builds only the freestanding objects (the"
    echo "# libc-independence proof); 'ninja build/quic_test' / 'ninja"
    echo "# fuzz/fuzz_<name>' opt into the heavier hosted/fuzz variants."
    echo "build freestanding: phony $objs"
    echo "default freestanding"
} > build.ninja
