#!/usr/bin/env python3
"""Convert BoringSSL FileTest vector files into C arrays for the test build.

Usage: scripts/gen_bssl_vectors.py tests/vectors/boringssl/<file>.txt [...]
Writes tests/vectors/boringssl/<stem>.h next to each input. The values are
kept as the vector file's raw text (hex, or a "quoted" string); the test-side
helpers in tests/vectors/boringssl/bssl_vec.h decode them. Nothing here
computes an expected value: every expectation comes from the vector file.

FileTest format: "KEY = value" or "KEY: value" is an attribute, "[k = v]" is
an instruction that applies to every following case, "#" starts a comment,
and a blank line ends a case.
"""
import os
import re
import sys

ATTR = re.compile(r'^([A-Za-z0-9_.-]+)\s*(?:=|:)\s*(.*)$')
INSTR = re.compile(r'^\[\s*([A-Za-z0-9_.-]+)\s*(?:=|:)?\s*(.*?)\s*\]$')


def c_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def parse(path):
    cases, cur, first, instr = [], [], 0, {}
    with open(path, encoding='utf-8') as f:
        lines = f.read().split('\n')
    for no, raw in enumerate(lines, 1):
        line = raw.strip()
        if not line or line.startswith('#'):
            if not line and cur:
                cases.append((first, no - 1, list(instr.items()) + cur))
                cur = []
            continue
        m = INSTR.match(line)
        if m:
            instr['[' + m.group(1)] = m.group(2)
            continue
        m = ATTR.match(line)
        if not m:
            raise SystemExit(f'{path}:{no}: unparsed line: {raw!r}')
        if not cur:
            first = no
        cur.append((m.group(1), m.group(2).strip()))
    if cur:
        cases.append((first, len(lines), list(instr.items()) + cur))
    return cases


def emit(path):
    stem = re.sub(r'\W', '_', os.path.splitext(os.path.basename(path))[0])
    cases = parse(path)
    out = os.path.join(os.path.dirname(path), stem + '.h')
    attrs, rows = [], []
    for first, last, kv in cases:
        rows.append((first, last, len(attrs), len(kv)))
        attrs.extend(kv)
    with open(out, 'w', encoding='utf-8') as f:
        f.write('/* clang-format off */\n')
        f.write(f'/* Generated by scripts/gen_bssl_vectors.py from\n'
                f' * {os.path.basename(path)}. Do not edit. */\n')
        f.write(f'static const bssl_attr bssl_{stem}_attrs[] = {{\n')
        for k, v in attrs:
            f.write(f'  {{{c_str(k)}, {c_str(v)}}},\n')
        f.write('};\n')
        f.write(f'static const bssl_case bssl_{stem}_cases[] = {{\n')
        for first, last, off, n in rows:
            f.write(f'  {{{first}, {last}, {off}, {n}}},\n')
        f.write('};\n/* clang-format on */\n')
    print(f'{out}: {len(cases)} cases')


for p in sys.argv[1:]:
    emit(p)
