#!/bin/sh
# Generate build.ninja covering every build this repo has: the freestanding
# per-object compile (proves libc independence), the libwired.a archive, the
# hosted unity-build test binary, the three libFuzzer harnesses, and the
# example server (release: links libwired.a; debug: recompiles the SDK with
# -DQUIC_DEBUG so the flag reaches in-SDK trace points). Each variant needs
# its own rule (different flags = incompatible .o ABIs, so they can't share
# object files), but all live in one build.ninja so `ninja <target>` builds
# any of them and `ninja` alone builds just the freestanding default.
set -eu

cc="${CC:-clang}"
# Flag sets come from justfile (single source of truth), passed as env vars.
: "${CFLAGS:?CFLAGS not set -- run via 'just gen-ninja'}"
: "${TESTFLAGS:?TESTFLAGS not set -- run via 'just gen-ninja'}"
: "${FUZZFLAGS:?FUZZFLAGS not set -- run via 'just gen-ninja'}"

srcs=$(find src -name '*.c' | sort)
objs=$(printf '%s\n' "$srcs" | sed 's|^|build/|; s|\.c$|.o|' | tr '\n' ' ')
# libwired.a excludes sys.o: its only symbol is the SDK's own _start stub,
# and applications supply their own entry point.
libobjs=$(printf '%s\n' "$srcs" | grep -v '^src/common/platform/sys/sys\.c$' \
    | sed 's|^|build/|; s|\.c$|.o|' | tr '\n' ' ')
# The debug example compiles the SDK from source (sys.c excluded, the example
# has its own _start) so -DQUIC_DEBUG reaches every trace point.
dbgsrcs=$(printf '%s\n' "$srcs" | grep -v '^src/common/platform/sys/sys\.c$' \
    | tr '\n' ' ')

{
    echo "# generated by scripts/gen_ninja.sh -- do not edit"
    echo "cc = $cc"
    echo "cflags = $CFLAGS"
    echo "testflags = $TESTFLAGS"
    echo "fuzzflags = $FUZZFLAGS"
    echo
    echo "rule cc_freestanding"
    echo "  command = \$cc \$cflags -MD -MF \$out.d -c \$in -o \$out"
    echo "  depfile = \$out.d"
    echo "  deps = gcc"
    echo "  description = CC \$out"
    echo
    echo "rule cc_hosted_bin"
    echo "  command = \$cc \$testflags \$in -o \$out"
    echo "  description = CC \$out"
    echo
    echo "rule cc_fuzz_bin"
    echo "  command = \$cc \$fuzzflags \$in -o \$out"
    echo "  description = CC \$out"
    echo
    echo "rule cc_freestanding_bin"
    echo "  command = \$cc \$cflags \$extra \$in -o \$out"
    echo "  description = CC \$out"
    echo
    echo "# rm first: ar rcs updates an existing archive in place, so a"
    echo "# member whose source was deleted would silently linger."
    echo "rule ar"
    echo "  command = rm -f \$out && ar rcs \$out \$in"
    echo "  description = AR \$out"
    echo
    echo "# freestanding: every src/**.c to build/<path>.o (path-qualified,"
    echo "# avoids basename collisions). Proves libc independence per file."
    printf '%s\n' "$srcs" | while read -r f; do
        echo "build build/${f%.c}.o: cc_freestanding $f"
    done
    echo
    echo "# hosted: tests/run.c is a unity build (includes every src/**.c and"
    echo "# *_test.c once), so it compiles straight to a binary -- no per-file"
    echo "# objects to track here."
    echo "build build/quic_test: cc_hosted_bin tests/run.c"
    echo
    echo "# fuzz: each harness includes its target src/**.c directly (hosted,"
    echo "# ASan+libFuzzer instrumented), same reasoning as the unity build."
    for name in header qpack x509; do
        echo "build fuzz/fuzz_$name: cc_fuzz_bin fuzz/fuzz_$name.c"
    done
    echo
    echo "# the SDK archive and the example server built against it."
    echo "build build/libwired.a: ar $libobjs"
    echo "build examples/word_list/wired_server: cc_freestanding_bin \$"
    echo "    examples/word_list/wired_server.c build/libwired.a"
    echo
    echo "# debug example: SDK recompiled from source with -DQUIC_DEBUG."
    echo "build examples/word_list/wired_server_debug: cc_freestanding_bin \$"
    echo "    examples/word_list/wired_server.c $dbgsrcs"
    echo "  extra = -DQUIC_DEBUG"
    echo
    echo "build examples/webtransport_echo/wired_server: cc_freestanding_bin \$"
    echo "    examples/webtransport_echo/wired_server.c build/libwired.a"
    echo
    echo "build examples/word_list_pinned/wired_server: cc_freestanding_bin \$"
    echo "    examples/word_list_pinned/wired_server.c build/libwired.a"
    echo
    echo "# 'ninja' with no args builds only the freestanding objects (the"
    echo "# libc-independence proof); everything else is opt-in by target."
    echo "build freestanding: phony $objs"
    echo "default freestanding"
} > build.ninja
